language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER invoicify WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  app: safe-river-21860
  api_key:
    secure: VNHt4iEwGcJBhVMOdk40/yS9cI6pQAc6xx/m60PP61d8xfQ1UrMdWegewLOsO4riSnJ9aOYZOV4dCIt7IT0vg0+Jm2LRKeAIUKlzPBpafmNGZgyaFwsu4IeZAn8+LnDZm3gZL5HzvDyFYyI8qmNGJcggumgnJHeOE04XQHImMZhQzauEznTt93YfL3m+RreUU+1OiK5ULP3q50qJXcKzq2XUHskGXmSRnKz772HTBzayj8HhBnABnxpDqSbtJHKbSXKjR0LHCnPW6V84ccDYKUeCV+NzC+9XlhQDmerubQkmy57HWy+KDXJhdIVYTLNP8RhOrXC5H7aVEXHSgdCEVynLku0YmO6dQ+8yFFLTH6owR1SAmJ5zm3abevw3kykYg7gbzPD/QYaaNfgiuLmuRvW89TIxwBH2QV1463uts+sGeJy6JDe8QeemnnYmU3cm49VOcqvoMs9u59gPMmlvtd2J5tB5nfEuXIc/LmL9WANN5s4t0LBp9YG2+fzBYaFv+oQwDzJGBRqwpMeqQm+A2iSBjlK+Rt+zkMg741JhcEuMaibYtFNRMp7GqC8AtQab3Uen63iXDJd0JcVixjLHELXf0j6Vad8ht4d7vvv74gjDm3dPWSSuCQEkASgm7Q1UdC7hGEzM/LnmH7T76clfe/w8mmLLJY2Tc7/g+OymkJ4=
