language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER invoicify WITH PASSWORD 'admin';" -U postgres
deploy:
  api_key:
    secure: Xjliu8wF5aWKn7SI46CmJmGO7KXoTP/c2sLpBJXznT2dj/+MnMJFLByOuInbLTSj1Ik69oIIB7pzic8OZVIfNJHTk4vOURUl/ByTR2comv1Aj3XrSc4tNljc+sS7oxLcR73bu8WKUuIDdLysZ0XILEJBbKSIEsLc7l+Dk1brSOJU7aeZ4ZxxXJBRetn2c7ks/ay53RaB79E1BRAVkRWazZ+ob3lJWDhS5NqLsUldmFyTQsLkEJctYd/sFITCn/R6+ZIkGpTWwb2S/xW5ZOfMmfbWQfU9ida0v34e9wYZrBOY61OYjnismFo9gc21FrUd8QMb8OVdoJdFd4EWsHQE2ggyfiPGYi3oAAqxDOgkQhICXFo3MaAzsFcIVRzyMjC6OXV51jaHEaxc+3fu5wC3nSxMRXVHM3A20oN5G+oIfOONdWL/LGSzFJKo4Zxz5z9u6qbWwGMBpM8ZSQqjlRQ3t+hIo/w1ekHlpu5+YnAmiI0HnEyDryPKTB/aQi2h4Li/s1oop6CfoKyNaikUwYQ6PN2E04VdGL/gRZsuTDNSOe89j4MKEsbCkDCNKEyI0FhM5YvQ/xhMvjpN97wCmXZToc4pn25q835m5X/mITvqRU6PKyAzJr3te8+iQAC2LIpPNkigCCrH+2dA5fPxinECoMk+4BTcqzIl87aAkW5GquQ=
  app: safe-river-21860